### ISSUE TITLE
SQLite3

### ISSUE THREAD

**Issue by donatelloferraz** [donatelloferraz/Danake#10]
Pesquisar, para criação do banco de dados, e como será feita suas requisições...

**Comment by GeorgeCandido** [comment]
Pessoal, achei alguns exemplos aqui a respeito do SQLite3 juntamente com a linguagem C. Bem fácil e didático o post criado no site tutorialspoint.com, segue aí e depois por favor deem uma olhada:
http://www.tutorialspoint.com/sqlite/sqlite_c_cpp.htm

**Comment by donatelloferraz** [comment]
Hoje no Hangouts eu mostro como instalar no windows/linux para os integrantes. Lembrando que no linux, esse tipo de instalação e dependências são bem mais simples.

**Comment by balaramr** [comment]
How do I build sqlite with static library also be compiled with -fPIC?
I have compiled using below parameters

# ./configure --prefix=/usr/local CFLAGS=-fPIC --enable-static --enable-shared     \
            CFLAGS="-g -O2 -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_SECURE_DELETE=1              \
            -DSQLITE_ENABLE_DBSTAT_VTAB=1"
# make -j 8
# make install

After using sqlite I get below error message: 

/usr/bin/g++ -o utools/utools.so -Wl,-Bsymbolic -g -O2 -shared -Wl,-z,defs utools/utools.plugin.o utools/lib/libutools.a core/lib/libunv.a fv/lib/libfv.a sb/lib/libsb.a -lz -ldl
/usr/bin/ld: /usr/local/sqlite/lib/libsqlite3.a(sqlite3.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/sqlite/lib/libsqlite3.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
scons: *** [stdarm/stdarm.so] Error 1
scons: building terminated because of errors.
